channels:
- conda-forge
dependencies:
- python=3.9.12
- pip<=21.2.4
- pip:
  - mlflow==2.4
  - cffi==1.15.0
  - cloudpickle==2.0.0
  - defusedxml==0.7.1
  - importlib-metadata==4.11.3
  - ipython==8.2.0
  - matplotlib==3.5.1
  - numpy==1.21.5
  - packaging==21.3
  - pandas==1.4.2
  - pathlib==1.0.1
  - psutil==5.8.0
  - pyyaml==6.0
  - scikit-learn==1.2.2
  - scipy==1.7.3
  - shap==0.41.0
name: mlflow-env
